//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chemical_Element
    {
        public int Number { get; set; }
        public string Symbol { get; set; }
        public string Name { get; set; }
        public double AtomicMass { get; set; }
        public string Configuration { get; set; }
        public double Electronegativity { get; set; }
        public string Oxidation { get; set; }
    }
}
